name: style

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v1
            - run: pip install cpplint
            - run: cpplint --recursive .